agora/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'agora.views.home', {'template':'landing.html'}),
    url(r'^hello/$', 'agora.views.hello', {'template':'hello.html'}),
    url(r'^login/$', 'agora.views.login', {'template':'login.html'}),
    url(r'^post/$', 'postapp.views.create_post', {'template':'create_post.html'}),
    url(r'^logout/$', 'agora.views.logout'),
    url(r'^create_post/$', 'postapp.views.create_post'),
    url(r'^process_create_post/$', 'postapp.views.process_create_post'),
    url(r'^post/vote/$', 'postapp.views.vote'),

    #url(r'^agora/', include('agora.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^admin/', include(admin.site.urls)),

    url(r'^post/(?P<pk>[0-9]+)$', 'agora.views.thread', {'template':'post_thread.html'}),

    url(r'^city/$', 'agora.views.city', {'template':'posts_for_town.html'}),
    url(r'^city/(?P<pk>[0-9]+)$', 'agora.views.allposts', {'template':'real_posts_for_town.html'}),
    url(r'^register/$', 'userapp.views.register', {'template':'create.html'}),


)

postapp/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

def file_name(instance, filename):
    return 'postpics/'+instance.pk+"/profile.jpg"

class Post(models.Model):
	post_date = models.DateTimeField(auto_now_add=True, null=True,blank=True)
	title = models.CharField(max_length=100,default="Title")
	city = models.ForeignKey('cityapp.City',related_name='posts')
	user = models.ForeignKey(User,related_name='posts')
	score = models.IntegerField(default=0)
	picture = models.ImageField(upload_to=file_name, max_length=200, blank=True, null=True)
	resolved = models.BooleanField(default=False) 
	content = models.TextField(max_length=1000, blank=False, null=False)

	def __unicode__(self):
		return self.title
	
class Vote(models.Model):
	post = models.ForeignKey(Post,related_name='votes')
	user = models.ForeignKey(User,related_name='votes')
	vote = models.BooleanField()
	def __unicode__(self):
		if self.vote:
			return self.user.first_name+" upvoted "+self.post.title
		else:
			return self.user.first_name+" downvoted "+self.post.title

class Comment(models.Model):
	post = models.ForeignKey(Post,related_name='comments')
	content = models.TextField(max_length=1000, blank=False, null=False)
	def __unicode__(self):
		return self.content

admin.site.register(Comment)
admin.site.register(Vote)
admin.site.register(Post)

userapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from userapp.models import UserProfile
from skills.living import livingGroups,majorChoices,yearChoices


class FullUserCreationForm(UserCreationForm):
    error_css_class = "error"


    hometown=models.ForeignKey("City")
    
    class Meta:
    	model = User
    
    def clean_email(self):
    	email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def clean_first_name(self):
        first = self.cleaned_data.get('first_name')
        if first=='' or first=="First":
            raise forms.ValidationError(u'First name is required.')
        return first 

    def clean_last_name(self):
        last = self.cleaned_data.get('last_name')
        if last=='' or last=="Last":
            raise forms.ValidationError(u'Last name is required.')
        return last    

    def clean_major(self):
        if self.cleaned_data['major']=='Major':
            raise forms.ValidationError(u'Please select a major.')
        return self.cleaned_data['major']

    def clean_livingGroup(self):
        if self.cleaned_data['livingGroup']=='Residence':
            raise forms.ValidationError(u'Please select a residence.')
        return self.cleaned_data['livingGroup']

    def clean_classYear(self):
        if self.cleaned_data['classYear']=='Class Year':
            raise forms.ValidationError(u'Please select a class year.')
        return self.cleaned_data['classYear']

    def save(self, commit=False):
        
        user = super(FullUserCreationForm, self).save(commit=False) 
        user.save()

        try:
            profile = user.get_profile()
        except:
            profile = UserProfile(user=user)

        profile.classYear = self.cleaned_data['classYear']
        profile.major = self.cleaned_data['major']
        profile.livingGroup = self.cleaned_data['livingGroup']
        if self.cleaned_data['picture']:
        	profile.picture = self.cleaned_data['picture']
        if self.cleaned_data['additional']:
        	profile.additional = self.cleaned_data['additional']
        profile.save()
        return user

class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea)
    

templates/change.html
{% extends 'template.html' %}
{% block head %}
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  {% endblock %}

  {% block body %}
  <div class="container-narrow" >

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
        <h4 class="muted"></h4>
      </div>

      

      <div class="jumbotron">
       
       
  <!-- /.carousel-inner -->
  <!--  Next and Previous controls below
        href values must reference the id for this carousel -->
    
</div>
        
        
        

        <h1><center>Welcome to GovernMaid!</center></h1>

        
        

        
       <center>
        
        <h3>Get Started</h3>
         <input type="text" data-provide="typeahead" data-items="2" autocomplete="off"
         data-source='["Chicago","New York","Boston","San Fransisco"]'><br></input><!-- Get the city Source -->
        <a href="#" class="btn btn-primary btn-large">Submit<br></a>
       
       </center>
       
     


     

      

      

      <div class="navbar navbar-fixed-bottom" align="right"> <p class="muted credit">GovernAid</p></div>

    </div> <!-- /container -->



    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>
    

  {% endblock %}

templates/create.html
{%  extends extension  %}


{% block headers %}
{% load staticfiles %}

<script>
$(function(){
  var width = $(window).width();
  if (width <980) {
    $("input").css({'max_width':'70px'});
  }



  $("input[name='first_name']").css({'color':'lightgrey'}).attr('value','First').addClass('django-input').focus(function(){
    if ($(this).val() == 'First' || $(this).val() == '' ) { 
      $(this).attr('value','');
    }
    $(this).css({'color':'black'});
  });
  
  $("input[name='first_name']").blur(function(){
    if ($(this).val() == '') {
      $(this).attr('value','First');
      $(this).css({'color':'LightGrey'});
    }
  });

  $("input[name='last_name']").css({'color':'lightgrey'}).attr('value','Last').addClass('django-input').focus(function(){
    if ($(this).val() == 'Last' || $(this).val() == '' ) { 
      $(this).attr('value','');
    }
    $(this).css({'color':'black'});
  });
  
  $("input[name='last_name']").blur(function(){
    if ($(this).val() == '') {
      $(this).attr('value','Last');
      $(this).css({'color':'LightGrey'});
    }
  });  

  $("input[name='email']").css({'color':'lightgrey'}).attr('value','Email').addClass('django-input').focus(function(){
    if ($(this).val() == 'Email' || $(this).val() == '' ) { 
      $(this).attr('value','');
    }
    $(this).css({'color':'black','font-size':'small !important'});
  });
  
  $("input[name='email']").blur(function(){
    if ($(this).val() == '') {
      $(this).attr('value','Email');
      $(this).css({'color':'LightGrey','font-size':'large'});
    }
  });

  $("textarea[name='additional']").attr('rows',10).css({'color':'black'}).html('A brief biography (background, interests, personal projects)').click(function(){
    if ($(this).html() == 'A brief biography (background, interests, personal projects)') { 
      $(this).html('A brief biography (background, interests, personal projects)');
    }
  });

  $("textarea[name='additional']").html('A brief biography (background, interests, personal projects)').blur(function(){
    if ($(this).html() == '') {
      $(this).html('A brief biography (background, interests, personal projects)');
    }
  });

});
</script>

{% endblock %}

{%  block body %}

{% if form %}
<script type="text/javascript">
  $(function(){
    $("#id_first_name").attr('value','{{ data.first_name }}').css({'color':'black'});
    $("#id_last_name").attr('value','{{ data.last_name }}').css({'color':'black'});
    $("#id_email").attr('value','{{ data.email }}').css({'color':'black'});
    $("#id_password1").attr('value','{{ data.password1 }}').css({'color':'black'});
    $("#id_password2").attr('value','{{ data.password2 }}').css({'color':'black'});
    $("#id_classYear").attr('value','{{ data.classYear }}').css({'color':'black'});
    $("#id_major").attr('value','{{ data.major }}').css({'color':'black'});
    $("#id_livingGroup").attr('value','{{ data.livingGroup }}').css({'color':'black'});
    $("#id_picture").attr('value','{{ data.picture }}').css({'color':'black'});
    $("#id_additional").attr('value','{{ data.additional }}').css({'color':'black'});

  });
</script>
{% endif %}
   
<form enctype="multipart/form-data" action="" method="post" >
    {% csrf_token %}
    <div class="responsive-icon visible-desktop" style="width:auto;margin-top:55px;max-width:200px">
      <div style="float:left">
        <i class="icon-check icon-white" style="margin-top:auto;margin-bottom:auto;"> </i>
      </div>
      <div style=""><strong>&nbsp;Smartphone-friendly site! </strong>
      </div>
    </div>   

{% if form.errors %}
{{ form.errors }}
    <div class="responsive-icon visible-desktop" style="background:darkred;position:absolute;top:10px;right:10px;width:auto;margin-top:55px;max-width:200px">
      <div style="float:right;margin-top:auto;margin-bottom:auto;color:white;">
        <i class="icon-exclamation-sign icon-white"> </i><strong>&nbsp;Correct the errors below.   </strong>         
      </div>
    </div>  
{% endif %}


{%  include 'navbar_create.html' %}

<div class="container">
  <div class="row-fluid">
    <div class="span6">
      <h2>Create Profile</h2><br/>
    </div>
  </div>
  <div class="row-fluid" style="">
    <div class="span2 visible-desktop" style="text-align:right;"><strong>The Person</strong></div>
    <div class="span2 hidden-desktop" style="text-align:left;"><strong>The Person</strong></div>
    <div class="span2" style="height:40px;">
      {{ form.first_name }}
      <span class="errors">
      &nbsp;&nbsp;&nbsp;{{ form.first_name.errors }}
      </span>  
    </div>
    <div class="span2 offset1 input_as_p">
      {{ form.last_name }}
      <span class="errors">
      &nbsp;&nbsp;&nbsp;{{ form.last_name.errors }}
      </span>
    </div>
    <div class="span2 offset1 input_as_p">
      {{ form.email }}
      <span class="errors">
      &nbsp;&nbsp;&nbsp;{{ form.email.errors }}
      </span>
    </div>
    <div class="offset2"></div>    
  </div>
  
  <hr/>

  <div class="row-fluid">
    <div class="span2 visible-desktop" style="text-align:right;"><strong>The Password</strong></div>
    <div class="span2 hidden-desktop" style="text-align:left;"><strong>The Password</strong></div>  
    {% if form.password2.errors %}
    <div class="span2 " style="color:darkred">{{ form.password2.errors }}</div>
    {% else %}
    <div class="span2 " style="color:black">Passwords should be eight characters long.  </div>

    {% endif %}
    <div class="span3 offset1">
      Password&nbsp;{{ form.password1 }}
      <span class="errors">
      </span>
    </div>
    <div class="span3 offset">
      Confirm&nbsp;{{ form.password2 }}
      <span class="errors">
      </span>
    </div>
  </div>
    <hr />


  <div class="row-fluid">
    <div class="span2 visible-desktop" style="text-align:right;"><strong>The Student</strong></div>
    <div class="span2 hidden-desktop" style="text-align:left;"><strong>The Student</strong></div>    
    <div class="span2" style="height:40px;">
      {{ form.classYear }}
      <span class="errors">
      &nbsp;&nbsp;&nbsp;{{ form.classYear.errors }}
      </span>
    </div>
    <div class="span2 offset1 input_as_p">
      {{ form.major }}
      <span class="errors">
      &nbsp;&nbsp;&nbsp;{{ form.major.errors }}
      </span>
    </div>
    <div class="span2 offset1 input_as_p">
      {{ form.livingGroup }}
      <span class="errors">
      &nbsp;&nbsp;&nbsp;{{ form.livingGroup.errors }}
      </span>
    </div>
    <div class="offset2"></div>    
  </div>
<hr/>
  <div class="row-fluid">
    <div class="span2 visible-desktop" style="text-align:right;"><strong>The Beautiful Individual</strong></div>
    <div class="span2 hidden-desktop" style="text-align:left;"><strong>The Beautiful Individual</strong></div>
    <div class="span2" style="height:40px;">
      Profile Picture
      <br/>
      {{ form.picture }}
      <span class="errors">
      &nbsp;&nbsp;&nbsp;{{ form.picture.errors }}
      </span>
    </div>
    <div class="span4 offset1">
      <div class="hidden-desktop" style="height:15px;"></div>
      {{ form.additional }}
      <span class="errors">
      &nbsp;&nbsp;&nbsp;{{ form.additional.errors }}
      </span>
    </div>
    <div class="offset2"></div>    
  </div>

  <div width="100%"><div class="center"><input type="submit" value="Proceed" class="btn btn-large btn-success center" /></div></div>
  </form>

{%  include "footer.html" %}
</div>


	
     
{% endblock %}

templates/create_post.html
{% extends 'template.html' %}
{% block head %}
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
 
    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }
 
      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }
 
      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }
 
      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">
 
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
 
    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  {% endblock %}
 
  {% block body %}
  <div class="container-narrow" >
 
        <div class="masthead">
              <ul class="nav nav-pills pull-right">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">About</a></li>
                  <li><a href="#">Contact</a></li>
              </ul>
            <h4 class="muted"></h4>
        </div>
           
<div class="jumbotron">
       <div class="container">
         <center>
            <div style="margin-top:40px;" class="row-fluid">
            <div class="page-header">
            <br><br><br><br><br><br><br><br>
            <h1>Submit an idea</h1>
            </div>
            </div>  
              <form name="input" action="/process_create_post/" method="POST">
            {% csrf_token %}
              <input type="text" name="title" post="content" id="content" style="width:600px; height:40px;" placeholder="Title">
            <br>
            <textarea name="content" cols="4" placeholder="Describe Your Idea"></textarea><br/>
            <button type="submit" class="btn btn-large btn-success" value="Submit!">Submit!</button>
            <a href="/city/1" class="btn btn-large">Back to Ideas</a>
             
</form>
</center>
 
 
 
 
<!--<form method="post" action="/enterskills/" autocomplete="off">
  {% csrf_token %}
  <div class="row-fluid">
    <div class="span6 offset3">
      <span style="font-weight:bold;font-size:large;">Enter Skills</span>
      <input type="text" id="enterbox" name="skills" id="typeahead" autocomplete="off" data-provide="typeahead" data-items="6" data-source='[{% for skill in allskills %}"{{ skill.name }}", {% endfor %} "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"]' >
    </div>
  </div>
 
  <div class="row-fluid" id="entered">
    <div width="1px" class="caboose"></div>
  </div>
  <div class="span2 offset5"><input width='100%' style="width:100%" type="submit" class="btn btn-large btn-success" value="Submit" /></div>
</form>-->
 
 
       
 
       
 
      <div class="navbar navbar-fixed-bottom" align="right"> <p class="muted credit">GovernAid</p></div>
 
    </div> <!-- /container -->
 
 
 
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>
   
 
  {% endblock %}

                        <form action="/process_create_post/" method="post">
              {% csrf_token %}
              <input class="span2" type="text" name="title" id="title" placeholder="Title">
              <input class="span2" type="text" name="content" id="content" placeholder="Write your idea here">
              <button type="submit" class="btn">Create post</button>
              <input type="hidden" name="city" value="test" />
            </form>

templates/login.html
			<form action="" method="post">
              {% csrf_token %}
              <input class="span2" type="text" name="username" id="username" placeholder="Username">
              <input class="span2" type="password" name="password" id="password"  placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
              <input type="hidden" name="next" value="/hello/" />
            </form>

templates/logout.html
{% extends 'template.html' %}
{% block head %}

    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
  {% endblock %}

  {% block body %}
  {% include "navbar_create.html" %}

  {% endblock %}

templates/navbar_create.html
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li id="about"><a href="#about">About</a></li>
              <li id="features"><a href="#contact">Features</a></li>
            </ul>
            <ul class="nav pull-right" style="margin-top:2px !important;">
              <input type="button" class="btn btn-small btn-success"  value="Logout" onclick="/logout/">
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

templates/navbar_login.html
  <div class="container-narrow" style="width:100% !important;">

      <div class="navbar navbar-inverse navbar-fixed-top" style="!margin-bottom:0px !important;">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Agora</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                        {% load staticfiles %}
              <!--<li><img style="display:inline;"src="{% static 'img/greek_column4.png' %}" alt="Greek Column"/></li>-->
              <li><a href="#anchor">About</a></li>
            </ul>
            <form class="navbar-form pull-right" action="/login/" method="post">
              {% csrf_token %}
              <input class="span2" type="text" name="username" id="username" placeholder="Username">
              <input class="span2" type="password" name="password" id="password"  placeholder="Password">
              <button type="submit" class="btn">Sign in</button>
              <input type="hidden" name="next" value="/you/" />
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>